[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

SECRETS_SCAN_OMIT_PATHS = "index.html report.html"

[[redirects]]
  from = "/report"
  to = "/report.html"
  status = 200

[[redirects]]
  from = "/report/*"
  to = "/report.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
